export const ROUTES = {
  dashboard: "/",
  fleet: "/fleet",
  vesselDetail: (imo: string) => `/fleet/${imo}`,
  voyages: "/voyages",
  voyageDetail: (id: string) => `/voyages/${id}`,
  ais: "/ais",
  marinetraffic: "/marinetraffic",
  documents: "/documents",
  documentDetail: (id: string) => `/documents/${id}`,
  review: "/review",
  reviewDetail: (id: string) => `/review/${id}`,
  ocr: "/ocr",
  compliance: "/compliance",
  euEts: "/eu-ets",
  dnv: "/dnv",
  analytics: "/analytics",
  settings: "/settings",
  settingsUsers: "/settings/users",
  settingsIntegrations: "/settings/integrations",
  settingsOrganization: "/settings/organization",
  settingsAppearance: "/settings/appearance",
  settingsNotifications: "/settings/notifications",
  login: "/login",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  assistant: "/assistant",
  complianceAssistant: "/compliance-assistant",
  poseidonSearch: "/search",
  captainAssistant: "/captain",
  maintenanceAssistant: "/maintenance",
  voyageAssistant: "/voyage",
  noon: "/noon",
} as const;
